### ISSUE TITLE
Examples for running custom topology

### ISSUE THREAD

**Issue by soutzis** [cnp3/ipmininet#9]
Hi Olivier,

Thank you for implementing this extension. I have been searching endlessly on the internet to find an implementation of an IPv6 Router.

I really want to use your library, but I am really quite unfamiliar with Mininet. I am trying to run your main file from examples, but I can't. Every time i get this error:
*** Adding Routers:
Could not find an executable for a daemon!Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/ipmininet/examples/__main__.py", line 62, in <module>
    net = IPNet(topo=TOPOS[args.topo](**kwargs), **NET_ARGS.get(args.topo, {}))
  File "/usr/local/lib/python2.7/dist-packages/ipmininet/ipnet.py", line 76, in __init__
    *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 174, in __init__
  File "/usr/local/lib/python2.7/dist-packages/ipmininet/ipnet.py", line 218, in build
    super(IPNet, self).build()
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 502, in build
  File "/usr/local/lib/python2.7/dist-packages/ipmininet/ipnet.py", line 105, in buildFromTopo
    self.addRouter(routerName, **topo.nodeInfo(routerName))
  File "/usr/local/lib/python2.7/dist-packages/ipmininet/ipnet.py", line 88, in addRouter
    r = cls(name, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/ipmininet/router/__router.py", line 93, in __init__
    self.config = config[0](self, **config[1])
  File "/usr/local/lib/python2.7/dist-packages/ipmininet/router/config/base.py", line 38, in __init__
    map(self.register_daemon, daemons)
  File "/usr/local/lib/python2.7/dist-packages/ipmininet/router/config/base.py", line 94, in register_daemon
    require_cmd(cls.NAME, 'Could not find an executable for a daemon!')
  File "/usr/local/lib/python2.7/dist-packages/ipmininet/utils.py", line 35, in require_cmd
    raise RuntimeError('[%s] is not available in $PATH' % cmd)
RuntimeError: [radvd] is not available in $PATH

Could you maybe add examples as to how to create a simple topology that can be run the same way that a Mininet topology can be run through a python script?

**Comment by soutzis** [comment]
Okay, the problem was that Router Advertisement Daemon (RADVD) was not installed on my computer. 
Thanks for this awesome library! So much time saved

**Comment by oliviertilmans** [comment]
Hi Petros,

The documentation sure needs to be improved.
Feel free to write down the questions you may have/the answers you found, this could be then integrated in a README/...


Best,
Olivier

**Comment by soutzis** [comment]
Hi Olivier,

I have found [this repository](https://github.com/obonaventure/RoutingExamples), that showcases the capabilities of IPMininet in a pretty great way. It also has an associated blog that explains the showcased examples further.

I think IPMininet has great potential and it would be my pleasure to help develop/improve good documentation for it (if you agree of course).

Best regards,
Petros Soutzis

**Comment by oliviertilmans** [comment]
Any pull request to improve the status quo would be welcome, especially as I have less time to allocate to this project. I am fine with providing feedback as needed, and wouldn't mind large code change if deemed necessary (e.g., to simplify/add syntactic sugar to the configuration process?).
Linking (potentially importing them if they bear a compatible license, with attributions) the examples from the cnp3 blog would also be interesting

@jadinm you may have ideas wrt. that.

**Comment by jadinm** [comment]
Hello,

A GPLv2 was just added on the examples of the cnp3 blog.
So, we can import them.

Mathieu

**Comment by jadinm** [comment]
I added some basic [documentation](https://ipmininet.readthedocs.io/en/latest/).
It is compiled from a [sphinx](http://www.sphinx-doc.org) project in the [docs](../tree/master/docs/) folder.

If you think that something is missing, incorrect or badly explained, don't hesitate to open a new issue or a PR ;)
